apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
  namespace: {{ .Release.Namespace }}
data:
  app.env: |-
    POSTGRES_SERVICE={{ .Values.global.postgres_service.name }}.{{ .Release.Namespace }}.svc.cluster.local